### ISSUE TITLE
User-Interface Mockups and Story board

### ISSUE THREAD

**Issue by Hitarth-Kothari** [CMPUT301F22T22/SnackOverflow#11]
Diagram the layout of your main user interface and major dialogs, with comments describing the important elements. Also, diagram storyboard sequences of using your application, with transitions between different states of the user interface, caused by the user manipulating the controls or providing input. Within the diagrams, reference the relevant requirements. Convincingly show all the requirements are covered.

**Comment by nidal312** [comment]
Completed: https://github.com/CMPUT301F22T22/SnackOverflow/wiki/User-Interface-Mockups-and-Storyboard-Sequences
