### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by Hitarth-Kothari** [CMPUT301F22T22/SnackOverflow#13]
Form the initial partial user stories into a backlog of the product's requirements. For each user story, estimate its size in story points, and denote its risk level (i.e., low, medium, or high). These requirements will likely evolve and should be maintained up-to-date throughout the project. Make sure they are numbered for easy reference. Note which stories will be released for the half-way checkpoint.

**Comment by nidal312** [comment]
Completed: https://github.com/CMPUT301F22T22/SnackOverflow/wiki/Product-Backlog
